- hosts : server
  tasks:
    - name: install python-docker ubuntu16
      apt:
        name: python-docker
        state: present
      when:
      - ansible_distribution == "Ubuntu"
    - name: pull image
      docker_image:
        name: hisbu/apache-ubuntu:latest
        source: pull
    - name: create container
      docker_container:
        name: container_by_jenkins
        image: hisbu/apache-ubuntu:latest
        state: started
        published_ports:
        - 9000:80
        recreate: yes
        interactive: yes
        detach: yes
